name: Build ALT package

on:
  workflow_dispatch:
  push:
    tags:
      # Only tags from altlinux branch
      - '*-alt*'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-altlinux:
    name: RPM build for sisyphus / amd64 and uploading
    runs-on: als-huge

    container:
      image: altlinux.space/alt-gnome/hasherc:latest

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog golang fuse-overlayfs

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: sisyphus
          arch: amd64

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/capsule/out/RPMS
          token: ${{ secrets.REGISTRY_TOKEN }}
          group: capsule/sisyphus
